# Generated by Django 5.2.7 on 2025-10-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userlink_clickevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
