# Generated by Django 5.2.7 on 2025-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userlink_clickevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClickEvent',
        ),
        migrations.DeleteModel(
            name='UserLink',
        ),
    ]
